In [328]:
import pandas as pd
import datetime

In [329]:
team_stats = pd.read_csv("../Data/teamstats.csv", parse_dates=['date'], date_format='%Y%m%d')

/tmp/ipykernel_150638/2076562708.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,44,46,61,63,99,110) have mixed types. Specify dtype option on import or set low_memory=False.
  team_stats = pd.read_csv("../Data/teamstats.csv", parse_dates=['date'], date_format='%Y%m%d')

# Cleaning & Preping team_stats.csv

In [330]:
print(team_stats.columns)
print(team_stats.shape)

Index(['gid', 'team', 'inn1', 'inn2', 'inn3', 'inn4', 'inn5', 'inn6', 'inn7',
       'inn8',
       ...
       'number', 'site', 'vishome', 'opp', 'win', 'loss', 'tie', 'gametype',
       'box', 'pbp'],
      dtype='object', length=111)
(488529, 111)

In [331]:
team_stats_cols_of_interest = ["gid", "team", "lob", "b_pa", "b_d", "b_t", "b_hr", "b_sb", "b_roe", "p_cs", "p_pb", "d_e", "d_sb", "date"]

team_stats2 = team_stats[team_stats_cols_of_interest]
# team_stats2.loc[:, 'date'] = pd.to_datetime(team_stats2['date'].astype(str), format='%Y%m%d', errors='coerce')

### rename columns to meaningful names

In [332]:
# rename columns to meaningful names
original_column_names = ["gid", "team", "lob", "b_pa", "b_d", "b_t", "b_hr", "b_sb", "b_roe", "p_cs", "p_pb", "d_e", "d_sb", "date"]
new_column_names = ["gid", "team", "left_on_base", "bat_plate_appear", "bat_doubles", "bat_triples", "bat_home_runs", "bat_stolen_bases", "bat_base_reaches_w_error", "caught_stealing_allowed", "passed_balls_allowed", "errors_committed", "stolen_bases", "date"]

team_stats2 = team_stats2.rename(columns=dict(zip(original_column_names, new_column_names)))
team_stats2.isna().sum()

gid                             0
team                            0
left_on_base                 7083
bat_plate_appear            56340
bat_doubles                  6458
bat_triples                  6724
bat_home_runs                5939
bat_stolen_bases             7319
bat_base_reaches_w_error    86066
caught_stealing_allowed     85846
passed_balls_allowed        56656
errors_committed             1229
stolen_bases                56844
date                            0
dtype: int64

 print initial unique values per column

In [333]:
def print_unique_values(df, ignore_cols=None):
    # unique values for each column
    if ignore_cols is None:
        ignore_cols = ["gid", "team", "date"]

    for col in df.columns:
        if col in ignore_cols:
            # ignore these columns as they dont have missing values
            continue
        col_unique_values = df[col].unique()
        col_na_count = int(df[col].isna().sum())
        print(f"{col}: {col_unique_values} \n{col_na_count=} \n")

print_unique_values(team_stats2)

left_on_base: [  6.  11.   3.   9.   7.   8.   5.   4.  10.  14.  12.  13.   2.   1.
  15.  16.  17.   0.  nan  20.  18.  19.  22.  21.  23.  24. -31.  25.
  27.  26.]
col_na_count=7083

bat_plate_appear: [ 45.  nan  32.  43.  34.  38.  41.  37.  36.  33.  44.  47.  39.  35.
  48.  50.  55.  51.  42.  40.  49.  57.  54.  46.  30.  31.  27.  29.
  24.  60.  52.  17.  19.  28.  23.  61.  58.  56.  16.  20.  59.  53.
  26.  22.  71.  65.  25.  73.  62.  72.  70.  63.  75.  18.  21.  66.
  67.  69.  15.  79.  77.  87.  89.  11.  64.  68.  80.  74.  13.  78.
  76.  93.  82.  84.  90.  96.  88.  85.  83.  95.  81.   4.  91.  86.
  92.  99. 103.  94. 104.]
col_na_count=56340

bat_doubles: [ 4.  2.  0.  3.  1.  5.  8.  7.  6.  9. 10. nan 12. 13. 11.]
col_na_count=6458

bat_triples: [ 4.  1.  0.  2.  3.  5. nan  6.  7.  8.]
col_na_count=6724

bat_home_runs: [ 0.  1.  2.  3. nan  4.  5.  7.  6.  8. 10.  9.]
col_na_count=5939

bat_stolen_bases: [ 3.  1.  0.  4.  2.  6.  5.  7.  8. nan 10. 11.  9. 13. 15. 12.]
col_na_count=7319

bat_base_reaches_w_error: [nan  3.  2.  1.  7.  5.  0.  4.  6.  8.  9.]
col_na_count=86066

caught_stealing_allowed: [nan  2.  0.  1.  3.  4.  5.  6.  7.]
col_na_count=85846

passed_balls_allowed: [ 0. nan  2.  1.  3.  5.  6.  4.]
col_na_count=56656

errors_committed: [ 3.  1.  0.  2.  4.  5.  7.  6.  8. 10.  9. 11. nan 12.]
col_na_count=1229

stolen_bases: [ 1. nan  3.  4.  0.  2.  6.  5.  7.  8. 10. 11.  9. 13. 15. 12.]
col_na_count=56844

In [334]:
# check column values bat_plate_appear: NA values
# 1985 - 2024
bat_plate_appear_na_rows = team_stats2[team_stats2["bat_plate_appear"].isna()]
print(bat_plate_appear_na_rows.shape)
bat_plate_appear_na_rows.head(5)

(56340, 14)

,gid,team,left_on_base,bat_plate_appear,bat_doubles,bat_triples,bat_home_runs,bat_stolen_bases,bat_base_reaches_w_error,caught_stealing_allowed,passed_balls_allowed,errors_committed,stolen_bases,date
1,PHI190104180,BRO,6.0,NaN,4.0,4.0,0.0,3.0,NaN,NaN,NaN,3.0,NaN,1901-04-18
5,BRO190104190,BRO,9.0,NaN,3.0,0.0,1.0,4.0,NaN,NaN,NaN,0.0,NaN,1901-04-19
7,BSN190104190,NY1,7.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2.0,NaN,1901-04-19
10,SLN190104190,CHN,8.0,NaN,2.0,2.0,0.0,2.0,NaN,NaN,NaN,2.0,NaN,1901-04-19
13,CIN190104200,PIT,6.0,NaN,0.0,3.0,0.0,0.0,NaN,NaN,NaN,2.0,NaN,1901-04-20

In [335]:
# Features to be dropped due to large nan count
drop_cols = ["bat_plate_appear", "bat_base_reaches_w_error", "caught_stealing_allowed"]
team_stats3_drop_too_many_nan = team_stats2.drop(drop_cols, axis=1)
team_stats3_drop_too_many_nan.shape

(488529, 11)

In [336]:
team_stats3_drop_too_many_nan.columns

Index(['gid', 'team', 'left_on_base', 'bat_doubles', 'bat_triples',
       'bat_home_runs', 'bat_stolen_bases', 'passed_balls_allowed',
       'errors_committed', 'stolen_bases', 'date'],
      dtype='object')

In [337]:
team_stats3_drop_too_many_nan.loc[team_stats3_drop_too_many_nan["left_on_base"].isna()].head()

,gid,team,left_on_base,bat_doubles,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date
2082,BLA190108210,DET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901-08-21
2083,BLA190108210,BLA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901-08-21
3921,BSN190206160,PIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902-06-16
3922,BSN190206160,BSN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902-06-16
4470,BLA190207170,SLA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902-07-17

In [338]:
# drop rows with multiple NaN values
team_stats4_clean = team_stats3_drop_too_many_nan.dropna(thresh=5)
team_stats4_clean.shape

(483424, 11)

In [339]:
team_stats4_clean.loc[team_stats4_clean["left_on_base"].isna()].head()

,gid,team,left_on_base,bat_doubles,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date
65900,ACY192007112,NYL,NaN,1.0,4.0,NaN,NaN,NaN,1.0,NaN,1920-07-11
65901,ACY192007112,ACY,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,1920-07-11
65912,NYL192007111,ACY,NaN,1.0,2.0,NaN,NaN,NaN,0.0,NaN,1920-07-11
65913,NYL192007111,NYL,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1920-07-11
89779,CAG192609292,CAG,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,1926-09-29

In [340]:
print_unique_values(team_stats4_clean)

left_on_base: [  6.  11.   3.   9.   7.   8.   5.   4.  10.  14.  12.  13.   2.   1.
  15.  16.  17.   0.  20.  18.  19.  22.  nan  21.  23.  24. -31.  25.
  27.  26.]
col_na_count=2002

bat_doubles: [ 4.  2.  0.  3.  1.  5.  8.  7.  6.  9. 10. 12. nan 13. 11.]
col_na_count=1377

bat_triples: [ 4.  1.  0.  2.  3.  5.  6. nan  7.  8.]
col_na_count=1631

bat_home_runs: [ 0.  1.  2.  3.  4.  5. nan  7.  6.  8. 10.  9.]
col_na_count=1006

bat_stolen_bases: [ 3.  1.  0.  4.  2.  6.  5.  7.  8. 10. 11.  9. 13. 15. nan 12.]
col_na_count=2216

passed_balls_allowed: [ 0. nan  2.  1.  3.  5.  6.  4.]
col_na_count=51553

errors_committed: [ 3.  1.  0.  2.  4.  5.  7.  6.  8. 10.  9. 11. nan 12.]
col_na_count=132

stolen_bases: [ 1. nan  3.  4.  0.  2.  6.  5.  7.  8. 10. 11.  9. 13. 15. 12.]
col_na_count=51741

#### clean columns with considerable fewer NaN values than others

In [341]:
# team_stats5_clean = team_stats4_clean.dropna(subset=['left_on_base', 'bat_doubles', 'bat_triples', 'bat_home_runs', 'bat_stolen_bases', 'errors_committed'])

In [342]:
# unique values after cleaning
# print_unique_values(team_stats5_clean)
# total_rows = team_stats5_clean.shape[0]
# print(f"Total rows: {total_rows}")

In [343]:
date_1985_clean_data = team_stats4_clean.loc[team_stats4_clean["date"] > datetime.datetime.strptime("1985-01-01", "%Y-%m-%d")]

date_1985_clean_data.isna().sum()

gid                     0
team                    0
left_on_base            0
bat_doubles             0
bat_triples             0
bat_home_runs           0
bat_stolen_bases        0
passed_balls_allowed    1
errors_committed        0
stolen_bases            1
date                    0
dtype: int64

In [344]:
date_1985_clean_data.head(10)

,gid,team,left_on_base,bat_doubles,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date
303402,BAL198504080,TEX,5.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1985-04-08
303403,BAL198504080,BAL,6.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1985-04-08
303404,BOS198504080,NYA,6.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1985-04-08
303405,BOS198504080,BOS,5.0,1.0,0.0,3.0,1.0,1.0,1.0,0.0,1985-04-08
303406,CIN198504080,MON,5.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,1985-04-08
303407,CIN198504080,CIN,8.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,1985-04-08
303408,DET198504080,CLE,6.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1985-04-08
303409,DET198504080,DET,10.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1985-04-08
303410,KCA198504080,TOR,7.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1985-04-08
303411,KCA198504080,KCA,6.0,2.0,0.0,0.0,0.0,0.0,2.0,1.0,1985-04-08

only columns [passed_balls_allowed, stolen_bases] has missing values. Maybe imputing will help with the value 0

In [345]:
date_1985_clean_data.loc[:, 'stolen_bases'] = date_1985_clean_data['stolen_bases'].fillna(0)
date_1985_clean_data.loc[:, 'passed_balls_allowed'] = date_1985_clean_data['passed_balls_allowed'].fillna(0)
date_1985_clean_data.to_csv("../CleanData/team_stats_04_27_25.csv")